// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrK6TOVoqG429Pzj3AceOSKwaFoz5BD9c',
    appId: '1:1048112503458:web:a3dcb5f853bf182ad055fb',
    messagingSenderId: '1048112503458',
    projectId: 'spotify1-7a12d',
    authDomain: 'spotify1-7a12d.firebaseapp.com',
    storageBucket: 'spotify1-7a12d.appspot.com',
    measurementId: 'G-8FCLK2BDT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjHIzMcZO6uSoW8oMv2_ZFbdNkrjbKQ0o',
    appId: '1:1048112503458:android:645a6c18fba6a719d055fb',
    messagingSenderId: '1048112503458',
    projectId: 'spotify1-7a12d',
    storageBucket: 'spotify1-7a12d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO33JX5twtmv2wWF2tRs_9Bg-eVSUdVDU',
    appId: '1:1048112503458:ios:75db58a9794dfe5ad055fb',
    messagingSenderId: '1048112503458',
    projectId: 'spotify1-7a12d',
    storageBucket: 'spotify1-7a12d.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO33JX5twtmv2wWF2tRs_9Bg-eVSUdVDU',
    appId: '1:1048112503458:ios:75db58a9794dfe5ad055fb',
    messagingSenderId: '1048112503458',
    projectId: 'spotify1-7a12d',
    storageBucket: 'spotify1-7a12d.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrK6TOVoqG429Pzj3AceOSKwaFoz5BD9c',
    appId: '1:1048112503458:web:651b7bb97276502cd055fb',
    messagingSenderId: '1048112503458',
    projectId: 'spotify1-7a12d',
    authDomain: 'spotify1-7a12d.firebaseapp.com',
    storageBucket: 'spotify1-7a12d.appspot.com',
    measurementId: 'G-VNHS443YH4',
  );
}
